### ISSUE TITLE
Exposed paths should always be separated by slashes

### ISSUE THREAD

**Issue by riesinger** [freecloudio/freecloud#101]
If we don't do this, we could expose that the underlying system is Windows, which might be a security problem (It probably shouldn't be, but come on... It's Windows).

This is easy to implement, just call `filepath.ToSlash()` on every path that gets exposed.

**Comment by TheHamloer** [comment]
This was fixed with issue #105 but I did not see the filepath function you mentioned...
Because of that this issue stays open to implement that given function

**Comment by riesinger** [comment]
Your function is more advanced, as it also combines multiple slashes into one. So I think we can now safely forget about the `filepath.ToSlash` function 😉 

```go
// ToSlash returns the result of replacing each separator character
  // in path with a slash ('/') character. Multiple separators are
  // replaced by multiple slashes.
  func ToSlash(path string) string {
  	if Separator == '/' {
  		return path
  	}
  	return strings.Replace(path, string(Separator), "/", -1)
  }
```

**Comment by TheHamloer** [comment]
Oh you are right I misread the docs..... Therefore this issue is closed now
