### ISSUE TITLE
Redesign of data API

### ISSUE THREAD

**Issue by TheHamloer** [freecloudio/freecloud#105]
We agreed to redesign the data API to the following endpoints:
- [x] `GET /download` Download one file
- [x] `POST /zip` Zips one or more files and returns the path to the generated zip
- [x] `POST /upload/path` Upload one file to the path given in the URL or a path given in the request body
- [x] `GET /path/path/to/smthing` Returns a json object with the fileInfo of the requested file/directory and in case of a directory a "files" array with the content
- [x] `POST /path/path/to/smthing` Creates an object at that path specified in the request body. Can be a directory or an empty file.
- [x] `PATCH /path/path/to/smthing` Renaming, moving, maybe copying and changing general information of a file or directory

For this in general we need some other utility:
- [x] A middleware to extract the path of the requests.
- [x] convertSlash function
- [x] Remove filename from path in the FileInfo
- [x] Add periodically removal of tmp files

**Comment by riesinger** [comment]
@TheHamloer what do you mean with "Middleware to extract the path"?

**Comment by TheHamloer** [comment]
A middleware that extracts the path of the file/directory the requests wants to address in the data map. With that we don't need to have the following code in every handler:
```go
path, err := url.PathUnescape(c.Params("*"))
if err != nil {
	c.Data["response"] = fmt.Errorf("Invalid directory format")
}
```
It could also directly do the slash conversion and so on
