### ISSUE TITLE
Exposed path contains filename

### ISSUE THREAD

**Issue by riesinger** [freecloudio/freecloud#106]
Currently, when getting a file, it returns sth. like the following:

```json
{
  "path": "/path/to/file.txt",
  "name": "file.txt"
}
```

whereas the expected response would be:

```json
{
  "path": "/path/to/",
  "name": "file.txt"
}
```

**Comment by TheHamloer** [comment]
This is already mentioned as a task in issue #105

**Comment by riesinger** [comment]
Whoopsie, closing this!
