### ISSUE TITLE
Create temp folder on startup

### ISSUE THREAD

**Issue by riesinger** [freecloudio/freecloud#112]
Currently, when starting up and the temp folder does not exist, we encounter an error:

```
[ WARN] Error reading temp folder in (Redacted)\go\src\github.com\freecloudio\freecloud\data\1\.tmp during temp cleanup: open (Redacted)\go\src\github.com\freecloudio\freecloud\data\1\.tmp: The system cannot find the file specified.
```

Maybe, we should also check whether the error returned is a "not found" error by using `os.IsNotExist` function and ignore the error in this case, as it is not a bad thing for the cleaner, if there is no temp dir.

**Comment by TheHamloer** [comment]
The problem is that the temp folder is only created when it is needed. So ignoring the error if the folder does not exist is a good solution :+1:

**Comment by riesinger** [comment]
We could also add a debug log to it like: 
```
[DEBUG] Temp folder does not exist for user <id>
```
