### ISSUE TITLE
Add 'star' flag to FileInfo and general implementation

### ISSUE THREAD

**Issue by TheHamloer** [freecloudio/freecloud#127]

**Comment by TheHamloer** [comment]
@riesinger Which extra features do you need for the frontend implementation? Getting all starred files for a user?

**Comment by riesinger** [comment]
@TheHamloer, yes, that's exactly what I need

**Comment by TheHamloer** [comment]
Anything else? 😅

**Comment by riesinger** [comment]
Probably not

**Comment by TheHamloer** [comment]
:+1:
