### ISSUE TITLE
File search

### ISSUE THREAD

**Issue by riesinger** [freecloudio/freecloud#129]
You should really be able to search for files, at least by their names, optionally also by their content

**Comment by TheHamloer** [comment]
For the search of filenames we can use a regex query in the database.
The query would be `` `(?i)filename\.txt` ``. 'i' for searching incasesensitive and all dots for file extensions need to be escaped with a backslash.

**Comment by riesinger** [comment]
So basically, we can do sth like `/api/v1/search/myfile` and just escape all special regex chars? Nice!

**Comment by riesinger** [comment]
just found [this](https://godoc.org/regexp#QuoteMeta)
