### ISSUE TITLE
Change a users data by signing him up again

### ISSUE THREAD

**Issue by TheHamloer** [freecloudio/freecloud#65]
Not only the db should check whether a user already exists and also it was possible to somehow change user data by creating a user twice. I don't know why this does not trigger a database error...

**Comment by riesinger** [comment]
Identified the issue as a bug in [storm](https://github.com/asdine/storm), so I opened an [issue there](https://github.com/asdine/storm/issues/200)

**Comment by TheHamloer** [comment]
This was fixed by #76
