### ISSUE TITLE
Design a proper API request/response scheme

### ISSUE THREAD

**Issue by riesinger** [freecloudio/freecloud#73]
Currently, the only thing that is "guaranteed" is the "success" field on successful requests and the "message" field on failed requests

**Comment by TheHamloer** [comment]
@riesinger With this we also should make a general overview on how we want our API to look like.
Do you know any tool to do this properly and collaborative? Otherwise Excel would also do this job 😜

**Comment by TheHamloer** [comment]
I guess with the new API this is kinda solved now
