### ISSUE TITLE
Do not expose full paths

### ISSUE THREAD

**Issue by riesinger** [freecloudio/freecloud#97]
Currently, we send the following to the frontend: 

![image](https://user-images.githubusercontent.com/6919894/35450066-2fc34724-02bf-11e8-9971-c0c9ee56afb1.png)

Which is wrong in many cases:

- It misses the user ID in the path?
- **We should _never ever ever_ expose the path freecloud runs in**

**Comment by TheHamloer** [comment]
When is this path sent? When listing the content of a directory?

**Comment by riesinger** [comment]
Jup
